# -*- coding: utf-8 -*-
#
# Copyright (C) 2020, Maximilian Köhl <mail@koehlma.de>
#
# This file has been automatically generated by:
# `python -m rigorous.semantics.python.basis generate-prelude`
#
# Do not modify this file manually!
#
# type: ignore
# flake8: noqa


raise AssertionError("this file should never be imported")
